### ISSUE TITLE
Update Classes structure according to latest "Concept Models"

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#26]
The Glossarist gem is supposed to implement the "Concept models" available here:
https://github.com/glossarist/concept-model

However, there are a number of features not yet available. This task is to enumerate all of those and implement them as Classes and attributes.

For example:
* [x] #27
* [x] #29 
* [x] #30
* [x] #33  
* [x] #34
* [x] #39 
* [x] #41 
* [x] #42

**Comment by ronaldtse** [comment]
The Glossarist gem is heavily used by the `iev-data` gem. We need to ensure that any updates to the Glossarist gem will be also updated accordingly in `iev-data`.

**Comment by ronaldtse** [comment]
@HassanAkbar could you help check the concept-models to see if we have implemented everything? If not please help elaborate this task, thanks.

**Comment by HassanAkbar** [comment]
> @HassanAkbar could you help check the concept-models to see if we have implemented everything? If not please help elaborate this task, thanks.

@ronaldtse We still have a few models missing. I'm working on it.

**Comment by ronaldtse** [comment]
Looks like it's done. Closing.
